/**
 * BuildWise AI — Interactive Demo Dataset
 * 
 * IMPORTANT: This sample dataset is strictly isolated for the public
 * "How It Works?" interactive walkthrough experience.
 * 
 * It must NEVER contaminate real user projects, runs, or database records.
 */

import type { CanonicalFloorPlan } from '../types/geometry'
import type { ComplianceResult, ComplianceSummary, Violation } from '../types/compliance'

export const DEMO_METADATA = {
  is_demo: true,
  demo_label: 'Interactive Sample Analysis',
  project_name: 'TechHub Executive Office Level 2 (Sample Project)',
  source_file: 'commercial_office_sample.dxf',
  occupancy_type: 'Business / Office',
  total_area_m2: 63.8,
  floor_count: 1,
  notes: 'Precomputed demonstration dataset showcasing automated geometric extraction, NetworkX topological routing, and NBC 2016 compliance evaluation.',
}

export const DEMO_FLOOR_PLAN: CanonicalFloorPlan = {
  id: 'demo-sample-01',
  version: '1.0',
  floor_count: 1,
  total_area_m2: 63.8,
  bounding_box: { xmin: 0, ymin: 0, xmax: 10, ymax: 8 },
  metadata: {
    source_format: 'dxf',
    source_filename: 'commercial_office_sample.dxf',
    extraction_method: 'ezdxf',
    coordinate_unit: 'meters',
    is_multi_floor: false,
    extraction_warnings: [],
    extraction_errors: [],
  },
  floors: [
    {
      level: 0,
      elevation_m: 0,
      rooms: [
        {
          id: 'room-101',
          room_type: 'living_room',
          label: 'Executive Conference Room',
          boundary: {
            vertices: [
              { x: 0, y: 0 },
              { x: 5, y: 0 },
              { x: 5, y: 4.5 },
              { x: 0, y: 4.5 },
            ],
          },
          area_m2: 22.5,
          floor_level: 0,
          confidence: 'high',
        },
        {
          id: 'room-102',
          room_type: 'bedroom',
          label: 'Private Office A',
          boundary: {
            vertices: [
              { x: 5, y: 0 },
              { x: 10, y: 0 },
              { x: 10, y: 4.5 },
              { x: 5, y: 4.5 },
            ],
          },
          area_m2: 22.5,
          floor_level: 0,
          confidence: 'high',
        },
        {
          id: 'room-103',
          room_type: 'corridor',
          label: 'Main Egress Corridor',
          boundary: {
            vertices: [
              { x: 0, y: 4.5 },
              { x: 10, y: 4.5 },
              { x: 10, y: 5.3 },
              { x: 0, y: 5.3 },
            ],
          },
          area_m2: 8.0,
          floor_level: 0,
          confidence: 'high',
        },
        {
          id: 'room-104',
          room_type: 'kitchen',
          label: 'Pantry / Breakroom',
          boundary: {
            vertices: [
              { x: 0, y: 5.3 },
              { x: 4, y: 5.3 },
              { x: 4, y: 8 },
              { x: 0, y: 8 },
            ],
          },
          area_m2: 10.8,
          floor_level: 0,
          confidence: 'high',
        },
      ],
      walls: [
        {
          id: 'w-1',
          wall_type: 'exterior',
          segments: [{ start: { x: 0, y: 0 }, end: { x: 10, y: 0 } }],
          thickness_m: 0.2,
          floor_level: 0,
          confidence: 'high',
        },
        {
          id: 'w-2',
          wall_type: 'exterior',
          segments: [{ start: { x: 10, y: 0 }, end: { x: 10, y: 8 } }],
          thickness_m: 0.2,
          floor_level: 0,
          confidence: 'high',
        },
        {
          id: 'w-3',
          wall_type: 'exterior',
          segments: [{ start: { x: 10, y: 8 }, end: { x: 0, y: 8 } }],
          thickness_m: 0.2,
          floor_level: 0,
          confidence: 'high',
        },
        {
          id: 'w-4',
          wall_type: 'exterior',
          segments: [{ start: { x: 0, y: 8 }, end: { x: 0, y: 0 } }],
          thickness_m: 0.2,
          floor_level: 0,
          confidence: 'high',
        },
        {
          id: 'w-5',
          wall_type: 'interior',
          segments: [{ start: { x: 5, y: 0 }, end: { x: 5, y: 4.5 } }],
          thickness_m: 0.15,
          floor_level: 0,
          confidence: 'high',
        },
        {
          id: 'w-6',
          wall_type: 'interior',
          segments: [{ start: { x: 0, y: 4.5 }, end: { x: 10, y: 4.5 } }],
          thickness_m: 0.15,
          floor_level: 0,
          confidence: 'high',
        },
      ],
      openings: [
        {
          id: 'op-1',
          opening_type: 'door',
          position: { x: 2.5, y: 4.5 },
          width_m: 0.75,
          floor_level: 0,
          confidence: 'high',
        },
        {
          id: 'op-2',
          opening_type: 'door',
          position: { x: 7.5, y: 4.5 },
          width_m: 1.0,
          floor_level: 0,
          confidence: 'high',
        },
        {
          id: 'op-3',
          opening_type: 'emergency_exit',
          position: { x: 10, y: 4.9 },
          width_m: 1.2,
          floor_level: 0,
          confidence: 'high',
        },
      ],
      stairs: [],
      exits: [
        {
          id: 'ex-1',
          position: { x: 10, y: 4.9 },
          exit_type: 'emergency_exit',
          width_m: 1.2,
          floor_level: 0,
          confidence: 'high',
        },
      ],
    },
  ],
}

export const DEMO_VIOLATIONS: Violation[] = [
  {
    id: 'viol-demo-001',
    compliance_result_id: 'cr-demo-001',
    rule_id: 'NBC-4-CW-001',
    title: 'Substandard Corridor Clear Width',
    severity: 'CRITICAL',
    status: 'FAIL',
    entity_type: 'corridor',
    geometry_hint: 'polygon',
    coordinates: [
      [0, 4.5],
      [10, 4.5],
      [10, 5.3],
      [0, 5.3],
    ],
    label_text: 'Corridor width 0.80m < 1.50m required',
    label_position: { x: 5, y: 4.9 },
    floor_level: 0,
    measured_value: 0.8,
    required_value: 1.5,
    difference: -0.7,
    unit: 'm',
    regulation_source: 'NBC 2016 Part 4 Table 8',
    recommendation:
      'Widen the main egress corridor from 0.80 m to at least 1.50 m clear width (shortfall: 0.70 m) to prevent fatal choke-points during emergency evacuation.',
    llm_explanation:
      'Under National Building Code 2016 Part 4 (Fire & Life Safety) Table 8, exit corridors serving commercial or business occupancies must maintain a continuous, unobstructed minimum clear width of 1.50 m. The current corridor measures only 0.80 m wide, posing severe risks of crush, bottlenecking, and smoke entrapment during high-density evacuation.',
    confidence: 'high',
  },
  {
    id: 'viol-demo-002',
    compliance_result_id: 'cr-demo-002',
    rule_id: 'NBC-4-DW-001',
    title: 'Conference Room Door Clear Width Below Standard',
    severity: 'MAJOR',
    status: 'FAIL',
    entity_type: 'opening',
    geometry_hint: 'point',
    coordinates: [[2.5, 4.5]],
    label_text: 'Door 0.75m < 0.90m',
    label_position: { x: 2.5, y: 4.5 },
    floor_level: 0,
    measured_value: 0.75,
    required_value: 0.9,
    difference: -0.15,
    unit: 'm',
    regulation_source: 'NBC 2016 Part 4 Section 4.3',
    recommendation:
      'Replace the 750 mm door leaf with a standard 900 mm or 1000 mm clear opening doorway (shortfall: 0.15 m).',
    llm_explanation:
      'Doors serving habitable or assembly spaces must have a clear opening width not less than 0.90 m (900 mm) to accommodate single-file wheelchair access and emergency egress without impediment.',
    confidence: 'high',
  },
  {
    id: 'viol-demo-003',
    compliance_result_id: 'cr-demo-004',
    rule_id: 'NBC-4-TD-001',
    title: 'Egress Travel Path Trace',
    severity: 'MINOR',
    status: 'PASS',
    entity_type: 'corridor',
    geometry_hint: 'polyline',
    coordinates: {
      polyline: [
        [2.5, 2.25],
        [2.5, 4.5],
        [10.0, 4.9],
      ],
      distance_m: 11.2,
      origin_room: 'Executive Conference Room',
      target_exit: 'Final Exit 1',
    },
    label_text: 'Egress path: 11.20m (Pass ≤ 30.0m)',
    label_position: { x: 6.0, y: 4.7 },
    floor_level: 0,
    measured_value: 11.2,
    required_value: 30.0,
    difference: -18.8,
    unit: 'm',
    regulation_source: 'NBC 2016 Part 4 Clause 4.5.1',
    recommendation: 'Egress distance complies safely with statutory maximum of 30.0 m.',
    confidence: 'high',
  },
]

export const DEMO_COMPLIANCE_RESULTS: ComplianceResult[] = [
  {
    id: 'cr-demo-001',
    rule_id: 'NBC-4-CW-001',
    title: 'Corridor Clear Width — Main Egress Corridor',
    description: 'Corridor clear width measured at 0.80 m vs statutory minimum of 1.50 m.',
    status: 'FAIL',
    severity: 'CRITICAL',
    measured_value: 0.8,
    required_value: 1.5,
    unit: 'm',
    regulation_source: 'NBC 2016 Part 4 Table 8',
    confidence: 'high',
    recommendation: 'Widen corridor to at least 1.50 m clear width (shortfall: 0.70 m).',
    llm_explanation:
      'Corridor width falls short of the 1.50 m fire safety requirement for commercial office corridors under Table 8.',
  },
  {
    id: 'cr-demo-002',
    rule_id: 'NBC-4-DW-001',
    title: 'Door Clear Width — Executive Conference Room',
    description: 'Door opening measured at 0.75 m vs statutory minimum of 0.90 m.',
    status: 'FAIL',
    severity: 'MAJOR',
    measured_value: 0.75,
    required_value: 0.9,
    unit: 'm',
    regulation_source: 'NBC 2016 Part 4 Section 4.3',
    confidence: 'high',
    recommendation: 'Replace door with standard 0.90 m clear opening (shortfall: 0.15 m).',
  },
  {
    id: 'cr-demo-003',
    rule_id: 'NBC-3-RA-001',
    title: 'Habitable Room Area — Conference Room',
    description: 'Room area measured at 22.50 m² vs statutory minimum of 9.50 m².',
    status: 'PASS',
    severity: 'MAJOR',
    measured_value: 22.5,
    required_value: 9.5,
    unit: 'm2',
    regulation_source: 'NBC 2016 Part 3 Clause 12.2',
    confidence: 'high',
    recommendation: 'Space complies with minimum area requirement.',
  },
  {
    id: 'cr-demo-004',
    rule_id: 'NBC-4-TD-001',
    title: 'Maximum Travel Distance to Exit',
    description: 'Topological Dijkstra egress walk distance measured at 11.20 m vs limit of 30.00 m.',
    status: 'PASS',
    severity: 'CRITICAL',
    measured_value: 11.2,
    required_value: 30.0,
    unit: 'm',
    regulation_source: 'NBC 2016 Part 4 Clause 4.5.1',
    confidence: 'high',
    recommendation: 'Travel distance is safely within statutory threshold.',
  },
  {
    id: 'cr-demo-005',
    rule_id: 'NBC-4-EX-001',
    title: 'Minimum Exit Count — Floor Level 0',
    description: 'Floor area is 63.8 m² with 1 exit door provided (required: 1).',
    status: 'PASS',
    severity: 'CRITICAL',
    measured_value: 1.0,
    required_value: 1.0,
    unit: 'count',
    regulation_source: 'NBC 2016 Part 4 Section 4.2',
    confidence: 'high',
    recommendation: 'Single exit is sufficient for single-story floor area under 500 m².',
  },
  {
    id: 'cr-demo-006',
    rule_id: 'NBC-4-DE-001',
    title: 'Corridor Dead-End Branch Limit',
    description: 'Circulation network verified without dead-end branches exceeding 6.00 m.',
    status: 'PASS',
    severity: 'CRITICAL',
    measured_value: 0.0,
    required_value: 6.0,
    unit: 'm',
    regulation_source: 'NBC 2016 Part 4 Clause 4.5.2',
    confidence: 'high',
    recommendation: 'Corridor circulation maintains continuous through-egress.',
  },
]

export const DEMO_COMPLIANCE_SUMMARY: ComplianceSummary = {
  total_checks: 6,
  passed: 4,
  failed: 2,
  unverified: 0,
  warning: 0,
  insufficient_data: 0,
  not_applicable: 0,
  compliance_score_pct: 66.7,
}

export const DEMO_GRAPH_DATA = {
  nodes: [
    { id: 'room-101', node_type: 'room', label: 'Executive Conf Room', centroid_x: 2.5, centroid_y: 2.25, floor_level: 0, confidence: 'high' },
    { id: 'room-102', node_type: 'room', label: 'Private Office A', centroid_x: 7.5, centroid_y: 2.25, floor_level: 0, confidence: 'high' },
    { id: 'room-103', node_type: 'corridor', label: 'Egress Corridor', centroid_x: 5.0, centroid_y: 4.9, floor_level: 0, confidence: 'high' },
    { id: 'room-104', node_type: 'room', label: 'Pantry / Breakroom', centroid_x: 2.0, centroid_y: 6.65, floor_level: 0, confidence: 'high' },
    { id: 'ex-1', node_type: 'exit', label: 'Exterior Exit 1', centroid_x: 10.0, centroid_y: 4.9, floor_level: 0, confidence: 'high' },
  ],
  edges: [
    { source_id: 'room-101', target_id: 'room-103', edge_type: 'door', width_m: 0.75 },
    { source_id: 'room-102', target_id: 'room-103', edge_type: 'door', width_m: 1.0 },
    { source_id: 'room-104', target_id: 'room-103', edge_type: 'door', width_m: 0.9 },
    { source_id: 'room-103', target_id: 'ex-1', edge_type: 'door', width_m: 1.2 },
  ],
  stats: { connected_components: 1, total_nodes: 5, total_edges: 4 },
}
